# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main
pr:
- master
pool:
  vmImage: ubuntu-latest
stages:
- stage: Installing_Requirements
  displayName: 'unit tests for User'
  jobs:
  - job: unit_tests
    steps:
    - script: |
        echo Wait ana stpn
      displayName: 'Installing Requirements'


- stage: Admin_User_Testing
  displayName: 'unit tests for User and admin'
  jobs:
  - job: unit_tests
    steps:
    - script: |
        pip install -r requirements.txt
      displayName: 'Installing Requirements'
    - script: |
        python main.py
      displayName: 'Running Website'
    - script: |
        pytest User_Testing.py
      displayName: 'Build Docker image for unit tests for user'
    - script: |
        pytest Admin_Testing.py
      displayName: 'Build Docker image for unit tests for admin'



- stage: build_push
  displayName: 'Build and push to docker hub'
  jobs:
  - job : build_push_job
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'MyDocker'
        repository: 'ezzat12/shaghalni'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.deploy'

    
