# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr:
- master
pool:
  vmImage: ubuntu-latest

stages:
- stage: test
  displayName: 'unit tests'
  jobs:
  - job: unit_tests
    steps:
    - script: |
        echo we will do unit tests here
      displayName: 'Build Docker image for unit tests'

    
